preset: none

risky: true

enabled:
  - align_double_arrow
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_before_return
  - cast_spaces
  - class_definition
  - combine_consecutive_unsets
  - concat_without_spaces
  - declare_equal_normalize
  - elseif
  - encoding
  - full_opening_tag
  - function_declaration
  - function_typehint_space
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - magic_constant_casing
  - method_argument_space
  - method_separation
  - method_visibility_required
  - native_function_casing
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_before_namespace
  - no_blank_lines_between_imports
  - no_closing_tag
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_null_property_initialization
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_after_function_name
  - no_spaces_inside_offset
  - no_spaces_inside_parenthesis
  - no_spaces_outside_offset
  - no_tab_indentation
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_unneeded_control_parentheses
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - object_operator_without_whitespace
  - php_unit_fqcn_annotation
  - phpdoc_add_missing_param_annotation
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_return_self_reference
  - phpdoc_scalar
  - phpdoc_to_comment
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - property_visibility_required
  - psr4
  - return_type_declaration
  - self_accessor
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - standardize_not_equals
  - switch_case_semicolon_to_colon
  - switch_case_space
  - unix_line_endings
  - whitespace_after_comma_in_array

finder:
  exclude:
    - "config"
    - "tests"
